-- V1: the entry table.
--
-- This file runs ONCE, ever. Flyway records it in flyway_schema_history
-- with a checksum, and refuses to start if the file changes afterwards.
-- Anything I want to alter later becomes V2.
--
-- It must be valid on BOTH H2 (MODE=PostgreSQL) and real Postgres, because
-- the same file runs in production in Section 8. So: standard SQL only.

CREATE TABLE entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_date DATE NOT NULL,
    description VARCHAR(255) NOT NULL,
    amount NUMERIC(12,2) NOT NULL
);

